export const mockData = {
    
        "data": [
          {
            "id": 1,
            "name": "John Smith",
            "email": "john.smith@example.com",
            "department": "Engineering",
            "position": "Senior Developer",
            "salary": 95000,
            "hireDate": "2022-03-15",
            "status": "Active",
            "projects": ["Web Platform", "Mobile App"],
            "performance": 4.2
          },
          {
            "id": 2,
            "name": "Sarah Johnson",
            "email": "sarah.j@example.com",
            "department": "Marketing",
            "position": "Marketing Manager",
            "salary": 82000,
            "hireDate": "2021-08-22",
            "status": "Active",
            "projects": ["Brand Refresh", "Social Media Campaign"],
            "performance": 4.5
          },
          {
            "id": 3,
            "name": "Michael Chen",
            "email": "m.chen@example.com",
            "department": "Engineering",
            "position": "Frontend Developer",
            "salary": 78000,
            "hireDate": "2023-01-10",
            "status": "Active",
            "projects": ["Web Platform"],
            "performance": 3.8
          },
          {
            "id": 4,
            "name": "Emily Davis",
            "email": "e.davis@example.com",
            "department": "Sales",
            "position": "Sales Director",
            "salary": 110000,
            "hireDate": "2020-06-15",
            "status": "Active",
            "projects": ["Enterprise Sales", "Partner Program"],
            "performance": 4.7
          },
          {
            "id": 5,
            "name": "Robert Wilson",
            "email": "r.wilson@example.com",
            "department": "HR",
            "position": "HR Manager",
            "salary": 75000,
            "hireDate": "2021-11-30",
            "status": "Active",
            "projects": ["Employee Engagement", "Recruitment"],
            "performance": 4.0
          },
          {
            "id": 6,
            "name": "Lisa Anderson",
            "email": "l.anderson@example.com",
            "department": "Engineering",
            "position": "QA Engineer",
            "salary": 72000,
            "hireDate": "2022-09-01",
            "status": "Active",
            "projects": ["Testing Automation"],
            "performance": 3.9
          },
          {
            "id": 7,
            "name": "David Martinez",
            "email": "d.martinez@example.com",
            "department": "Product",
            "position": "Product Manager",
            "salary": 98000,
            "hireDate": "2021-03-22",
            "status": "Active",
            "projects": ["Mobile App", "User Research"],
            "performance": 4.4
          },
          {
            "id": 8,
            "name": "Jennifer Lee",
            "email": "j.lee@example.com",
            "department": "Design",
            "position": "UI/UX Designer",
            "salary": 80000,
            "hireDate": "2022-07-15",
            "status": "Active",
            "projects": ["Design System", "Mobile App"],
            "performance": 4.3
          },
          {
            "id": 9,
            "name": "William Brown",
            "email": "w.brown@example.com",
            "department": "Engineering",
            "position": "Backend Developer",
            "salary": 85000,
            "hireDate": "2021-12-10",
            "status": "Active",
            "projects": ["API Development", "Database Migration"],
            "performance": 4.1
          },
          {
            "id": 10,
            "name": "Maria Garcia",
            "email": "m.garcia@example.com",
            "department": "Marketing",
            "position": "Content Strategist",
            "salary": 70000,
            "hireDate": "2023-02-28",
            "status": "Active",
            "projects": ["Content Calendar", "Blog Strategy"],
            "performance": 3.8
          },
          {
            "id": 11,
            "name": "James Wilson",
            "email": "j.wilson@example.com",
            "department": "Engineering",
            "position": "DevOps Engineer",
            "salary": 92000,
            "hireDate": "2022-04-18",
            "status": "Active",
            "projects": ["CI/CD Pipeline", "Cloud Migration"],
            "performance": 4.4
          },
          {
            "id": 12,
            "name": "Patricia Moore",
            "email": "p.moore@example.com",
            "department": "Sales",
            "position": "Account Executive",
            "salary": 85000,
            "hireDate": "2021-09-15",
            "status": "Active",
            "projects": ["Enterprise Sales"],
            "performance": 4.2
          },
          {
            "id": 13,
            "name": "Thomas Taylor",
            "email": "t.taylor@example.com",
            "department": "Engineering",
            "position": "Software Architect",
            "salary": 120000,
            "hireDate": "2020-08-01",
            "status": "Active",
            "projects": ["System Architecture", "Tech Strategy"],
            "performance": 4.8
          },
          {
            "id": 14,
            "name": "Jessica White",
            "email": "j.white@example.com",
            "department": "Product",
            "position": "Product Analyst",
            "salary": 72000,
            "hireDate": "2022-11-07",
            "status": "Active",
            "projects": ["Analytics Dashboard", "User Research"],
            "performance": 3.9
          },
          {
            "id": 15,
            "name": "Daniel Lee",
            "email": "d.lee@example.com",
            "department": "Engineering",
            "position": "Mobile Developer",
            "salary": 88000,
            "hireDate": "2021-06-22",
            "status": "Active",
            "projects": ["Mobile App", "SDK Development"],
            "performance": 4.3
          },
          {
            "id": 16,
            "name": "Michelle Rodriguez",
            "email": "m.rodriguez@example.com",
            "department": "HR",
            "position": "HR Specialist",
            "salary": 65000,
            "hireDate": "2023-01-15",
            "status": "Active",
            "projects": ["Employee Benefits", "Onboarding"],
            "performance": 3.7
          },
          {
            "id": 17,
            "name": "Christopher Martin",
            "email": "c.martin@example.com",
            "department": "Engineering",
            "position": "Security Engineer",
            "salary": 95000,
            "hireDate": "2021-10-11",
            "status": "Active",
            "projects": ["Security Audit", "Penetration Testing"],
            "performance": 4.5
          },
          {
            "id": 18,
            "name": "Amanda Thompson",
            "email": "a.thompson@example.com",
            "department": "Marketing",
            "position": "Digital Marketing",
            "salary": 68000,
            "hireDate": "2022-08-30",
            "status": "Active",
            "projects": ["SEO Strategy", "PPC Campaigns"],
            "performance": 4.0
          },
          {
            "id": 19,
            "name": "Kevin Anderson",
            "email": "k.anderson@example.com",
            "department": "Sales",
            "position": "Sales Manager",
            "salary": 95000,
            "hireDate": "2021-04-05",
            "status": "Active",
            "projects": ["Sales Strategy", "Team Development"],
            "performance": 4.6
          },
          {
            "id": 20,
            "name": "Laura Martinez",
            "email": "l.martinez@example.com",
            "department": "Design",
            "position": "Graphic Designer",
            "salary": 70000,
            "hireDate": "2022-12-01",
            "status": "Active",
            "projects": ["Brand Assets", "Marketing Materials"],
            "performance": 4.1
          },
          {
            "id": 21,
            "name": "Ryan Collins",
            "email": "r.collins@example.com",
            "department": "Engineering",
            "position": "Data Engineer",
            "salary": 90000,
            "hireDate": "2021-07-19",
            "status": "Active",
            "projects": ["Data Pipeline", "Analytics Infrastructure"],
            "performance": 4.3
          },
          {
            "id": 22,
            "name": "Nicole Wright",
            "email": "n.wright@example.com",
            "department": "Product",
            "position": "Product Owner",
            "salary": 88000,
            "hireDate": "2022-02-14",
            "status": "Active",
            "projects": ["Product Roadmap", "Feature Planning"],
            "performance": 4.2
          },
          {
            "id": 23,
            "name": "Steven King",
            "email": "s.king@example.com",
            "department": "Engineering",
            "position": "Systems Engineer",
            "salary": 87000,
            "hireDate": "2021-11-08",
            "status": "Active",
            "projects": ["Infrastructure", "System Monitoring"],
            "performance": 4.0
          },
          {
            "id": 24,
            "name": "Rachel Green",
            "email": "r.green@example.com",
            "department": "Marketing",
            "position": "PR Specialist",
            "salary": 72000,
            "hireDate": "2022-06-27",
            "status": "Active",
            "projects": ["Media Relations", "Press Releases"],
            "performance": 3.9
          },
          {
            "id": 25,
            "name": "Eric Scott",
            "email": "e.scott@example.com",
            "department": "Engineering",
            "position": "Full Stack Developer",
            "salary": 92000,
            "hireDate": "2021-05-03",
            "status": "Active",
            "projects": ["Web Platform", "Internal Tools"],
            "performance": 4.4
          },
          {
            "id": 26,
            "name": "Catherine Baker",
            "email": "c.baker@example.com",
            "department": "HR",
            "position": "Training Coordinator",
            "salary": 63000,
            "hireDate": "2022-10-17",
            "status": "Active",
            "projects": ["Employee Training", "Skill Development"],
            "performance": 3.8
          },
          {
            "id": 27,
            "name": "Frank Turner",
            "email": "f.turner@example.com",
            "department": "Sales",
            "position": "Business Developer",
            "salary": 78000,
            "hireDate": "2021-08-09",
            "status": "Active",
            "projects": ["Market Expansion", "Partnership Development"],
            "performance": 4.1
          },
          {
            "id": 28,
            "name": "Diana Ross",
            "email": "d.ross@example.com",
            "department": "Design",
            "position": "Product Designer",
            "salary": 82000,
            "hireDate": "2022-03-28",
            "status": "Active",
            "projects": ["Product Design", "User Experience"],
            "performance": 4.5
          },
          {
            "id": 29,
            "name": "Gregory Hughes",
            "email": "g.hughes@example.com",
            "department": "Engineering",
            "position": "Cloud Engineer",
            "salary": 94000,
            "hireDate": "2021-12-06",
            "status": "Active",
            "projects": ["Cloud Architecture", "Cost Optimization"],
            "performance": 4.3
          },
          {
            "id": 30,
            "name": "Helen Foster",
            "email": "h.foster@example.com",
            "department": "Marketing",
            "position": "SEO Specialist",
            "salary": 69000,
            "hireDate": "2022-07-11",
            "status": "Active",
            "projects": ["SEO Strategy", "Content Optimization"],
            "performance": 3.9
          },
          {
            "id": 31,
            "name": "Peter Morgan",
            "email": "p.morgan@example.com",
            "department": "Engineering",
            "position": "Database Admin",
            "salary": 89000,
            "hireDate": "2021-09-20",
            "status": "Active",
            "projects": ["Database Management", "Performance Tuning"],
            "performance": 4.2
          },
          {
            "id": 32,
            "name": "Sandra Phillips",
            "email": "s.phillips@example.com",
            "department": "Product",
            "position": "UX Researcher",
            "salary": 76000,
            "hireDate": "2022-04-04",
            "status": "Active",
            "projects": ["User Research", "Usability Testing"],
            "performance": 4.0
          },
          {
            "id": 33,
            "name": "Brian Cooper",
            "email": "b.cooper@example.com",
            "department": "Sales",
            "position": "Sales Representative",
            "salary": 71000,
            "hireDate": "2021-10-25",
            "status": "Active",
            "projects": ["Lead Generation", "Client Relations"],
            "performance": 3.8
          },
          {
            "id": 34,
            "name": "Margaret Butler",
            "email": "m.butler@example.com",
            "department": "HR",
            "position": "Recruitment Specialist",
            "salary": 67000,
            "hireDate": "2022-01-31",
            "status": "Active",
            "projects": ["Talent Acquisition", "Employer Branding"],
            "performance": 4.1
          },
          {
            "id": 35,
            "name": "Kenneth Ward",
            "email": "k.ward@example.com",
            "department": "Engineering",
            "position": "ML Engineer",
            "salary": 98000,
            "hireDate": "2021-06-14",
            "status": "Active",
            "projects": ["ML Models", "Data Science"],
            "performance": 4.6
          },
          {
            "id": 36,
            "name": "Carol Reed",
            "email": "c.reed@example.com",
            "department": "Marketing",
            "position": "Social Media Manager",
            "salary": 65000,
            "hireDate": "2022-11-21",
            "status": "Active",
            "projects": ["Social Media Strategy", "Community Management"],
            "performance": 3.9
          },
          
          {
            "id": 36,
            "name": "Carol Reed",
            "email": "c.reed@example.com",
            "department": "Marketing",
            "position": "Social Media Manager",
            "salary": 65000,
            "hireDate": "2022-11-21",
            "status": "Active",
            "projects": ["Social Media Strategy", "Community Management"],
            "performance": 3.9
          },
          {
            "id": 37,
            "name": "Marcus Chen",
            "email": "m.chen@example.com",
            "department": "Engineering",
            "position": "Software Developer",
            "salary": 85000,
            "hireDate": "2023-01-15",
            "status": "Active",
            "projects": ["Backend API", "Database Migration"],
            "performance": 4.2
          },
          {
            "id": 38,
            "name": "Sarah Johnson",
            "email": "s.johnson@example.com",
            "department": "Sales",
            "position": "Account Executive",
            "salary": 75000,
            "hireDate": "2023-02-01",
            "status": "Active",
            "projects": ["Client Acquisition", "Sales Strategy"],
            "performance": 4.5
          },
          {
            "id": 39,
            "name": "David Kim",
            "email": "d.kim@example.com",
            "department": "IT",
            "position": "System Administrator",
            "salary": 72000,
            "hireDate": "2023-03-10",
            "status": "Active",
            "projects": ["Network Security", "Cloud Migration"],
            "performance": 4.0
          },
          {
            "id": 40,
            "name": "Emily Brown",
            "email": "e.brown@example.com",
            "department": "HR",
            "position": "HR Specialist",
            "salary": 62000,
            "hireDate": "2023-04-05",
            "status": "Active",
            "projects": ["Employee Training", "Recruitment"],
            "performance": 3.8
          },
          {
            "id": 41,
            "name": "Michael Torres",
            "email": "m.torres@example.com",
            "department": "Engineering",
            "position": "Frontend Developer",
            "salary": 80000,
            "hireDate": "2023-05-15",
            "status": "Active",
            "projects": ["UI Redesign", "Mobile App"],
            "performance": 4.1
          },
          {
            "id": 42,
            "name": "Lisa Wang",
            "email": "l.wang@example.com",
            "department": "Finance",
            "position": "Financial Analyst",
            "salary": 70000,
            "hireDate": "2023-06-01",
            "status": "Active",
            "projects": ["Budget Planning", "Financial Reports"],
            "performance": 4.3
          },
          {
            "id": 43,
            "name": "James Wilson",
            "email": "j.wilson@example.com",
            "department": "Marketing",
            "position": "Content Manager",
            "salary": 68000,
            "hireDate": "2023-07-12",
            "status": "Active",
            "projects": ["Content Strategy", "Brand Development"],
            "performance": 3.7
          },
          {
            "id": 44,
            "name": "Anna Martinez",
            "email": "a.martinez@example.com",
            "department": "Sales",
            "position": "Sales Manager",
            "salary": 82000,
            "hireDate": "2023-08-20",
            "status": "Active",
            "projects": ["Team Leadership", "Revenue Growth"],
            "performance": 4.4
          },
          {
            "id": 45,
            "name": "Robert Park",
            "email": "r.park@example.com",
            "department": "IT",
            "position": "Security Engineer",
            "salary": 88000,
            "hireDate": "2023-09-05",
            "status": "Active",
            "projects": ["Security Audit", "Penetration Testing"],
            "performance": 4.6
          },
          {
            "id": 46,
            "name": "Jessica White",
            "email": "j.white@example.com",
            "department": "HR",
            "position": "HR Manager",
            "salary": 78000,
            "hireDate": "2023-10-15",
            "status": "Active",
            "projects": ["Recruitment Strategy", "Employee Benefits"],
            "performance": 4.2
          },
          {
            "id": 47,
            "name": "David Lee",
            "email": "  d.lee@example.com",
            "department": "Engineering",
            "position": "Backend Developer",
            "salary": 86000,
            "hireDate": "2023-11-10",
            "status": "Active",
            "projects": ["API Development", "Database Optimization"],
            "performance": 4
          },

          {
            "id": 48,
            "name": "Sophia Turner",
            "email": "sophia.turner@example.com",
            "department": "Design",
            "position": "UI/UX Designer",
            "salary": 72000,
            "hireDate": "2021-07-15",
            "status": "Active",
            "projects": ["App Redesign", "Accessibility Audit"],
            "performance": 5
          },
          {
            "id": 49,
            "name": "Michael Brown",
            "email": "michael.brown@example.com",
            "department": "Engineering",
            "position": "Frontend Developer",
            "salary": 81000,
            "hireDate": "2022-03-08",
            "status": "Active",
            "projects": ["Component Library", "Performance Optimization"],
            "performance": 3
          },
          {
            "id": 50,
            "name": "Emily Davis",
            "email": "emily.davis@example.com",
            "department": "Marketing",
            "position": "Content Strategist",
            "salary": 65000,
            "hireDate": "2020-05-20",
            "status": "Inactive",
            "projects": ["SEO Strategy", "Blog Revamp"],
            "performance": 4
          },
          {
            "id": 51,
            "name": "James Wilson",
            "email": "james.wilson@example.com",
            "department": "HR",
            "position": "Recruitment Manager",
            "salary": 58000,
            "hireDate": "2019-12-11",
            "status": "Active",
            "projects": ["Employee Retention Plan", "Interview Workflow Improvement"],
            "performance": 5
          },
          {
            "id": 52,
            "name": "Olivia Martinez",
            "email": "olivia.martinez@example.com",
            "department": "Finance",
            "position": "Financial Analyst",
            "salary": 73000,
            "hireDate": "2022-06-18",
            "status": "Active",
            "projects": ["Budget Planning", "Cost Analysis"],
            "performance": 4
          },
          {
            "id": 53,
            "name": "Liam Moore",
            "email": "liam.moore@example.com",
            "department": "Engineering",
            "position": "DevOps Engineer",
            "salary": 91000,
            "hireDate": "2023-01-09",
            "status": "Active",
            "projects": ["Infrastructure Automation", "CI/CD Pipeline"],
            "performance": 3
          },
          {
            "id": 54,
            "name": "Amelia Johnson",
            "email": "amelia.johnson@example.com",
            "department": "Customer Support",
            "position": "Support Specialist",
            "salary": 42000,
            "hireDate": "2020-09-12",
            "status": "Active",
            "projects": ["Help Desk Overhaul", "Customer Experience Survey"],
            "performance": 4
          },
          {
            "id": 55,
            "name": "Ethan Clark",
            "email": "ethan.clark@example.com",
            "department": "Engineering",
            "position": "Full Stack Developer",
            "salary": 88000,
            "hireDate": "2022-02-27",
            "status": "Active",
            "projects": ["Cross-platform Integration", "Code Quality Improvement"],
            "performance": 4
          },
          {
            "id": 56,
            "name": "Charlotte Harris",
            "email": "charlotte.harris@example.com",
            "department": "Sales",
            "position": "Account Manager",
            "salary": 70000,
            "hireDate": "2018-08-03",
            "status": "Inactive",
            "projects": ["Enterprise Deals", "Client Retention Strategy"],
            "performance": 5
          },
          {
            "id": 57,
            "name": "Noah Walker",
            "email": "noah.walker@example.com",
            "department": "Engineering",
            "position": "Data Scientist",
            "salary": 95000,
            "hireDate": "2023-04-22",
            "status": "Active",
            "projects": ["Predictive Analytics", "Data Visualization Dashboard"],
            "performance": 4
          },
          {
            "id": 58,
            "name": "Ella Scott",
            "email": "ella.scott@example.com",
            "department": "Product Management",
            "position": "Product Manager",
            "salary": 96000,
            "hireDate": "2021-10-16",
            "status": "Active",
            "projects": ["Feature Roadmap", "User Research"],
            "performance": 5
          },
          {
            "id": 59,
            "name": "Aiden Young",
            "email": "aiden.young@example.com",
            "department": "Engineering",
            "position": "QA Engineer",
            "salary": 69000,
            "hireDate": "2020-07-25",
            "status": "Active",
            "projects": ["Test Automation", "Bug Tracking"],
            "performance": 4
          },
          {
            "id": 60,
            "name": "Isabella King",
            "email": "isabella.king@example.com",
            "department": "Operations",
            "position": "Operations Analyst",
            "salary": 62000,
            "hireDate": "2019-03-30",
            "status": "Inactive",
            "projects": ["Process Optimization", "Logistics Planning"],
            "performance": 3
          },
          {
            "id": 61,
            "name": "Lucas Wright",
            "email": "lucas.wright@example.com",
            "department": "Sales",
            "position": "Sales Representative",
            "salary": 68000,
            "hireDate": "2022-05-05",
            "status": "Active",
            "projects": ["Client Acquisition", "Market Expansion"],
            "performance": 4
          },
          {
            "id": 62,
            "name": "Grace Hall",
            "email": "grace.hall@example.com",
            "department": "Finance",
            "position": "Accountant",
            "salary": 75000,
            "hireDate": "2023-02-15",
            "status": "Active",
            "projects": ["Tax Filing", "Audit Preparation"],
            "performance": 5
          },
          {
            "id": 63,
            "name": "Benjamin Martinez",
            "email": "benjamin.martinez@example.com",
            "department": "Engineering",
            "position": "Machine Learning Engineer",
            "salary": 110000,
            "hireDate": "2023-09-01",
            "status": "Active",
            "projects": ["Recommendation System", "AI Model Deployment"],
            "performance": 5
          },
          {
            "id": 64,
            "name": "Mia Carter",
            "email": "mia.carter@example.com",
            "department": "Marketing",
            "position": "Social Media Manager",
            "salary": 58000,
            "hireDate": "2020-11-10",
            "status": "Active",
            "projects": ["Campaign Launch", "Brand Partnerships"],
            "performance": 4
          },
          {
            "id": 65,
            "name": "Logan Hill",
            "email": "logan.hill@example.com",
            "department": "IT",
            "position": "System Administrator",
            "salary": 74000,
            "hireDate": "2021-04-08",
            "status": "Active",
            "projects": ["Network Security", "Server Maintenance"],
            "performance": 4
          },
          {
            "id": 66,
            "name": "Lily Perez",
            "email": "lily.perez@example.com",
            "department": "HR",
            "position": "HR Specialist",
            "salary": 53000,
            "hireDate": "2022-12-19",
            "status": "Active",
            "projects": ["Onboarding Program", "Benefits Management"],
            "performance": 3
          },
          {
            "id": 67,
            "name": "Ethan Adams",
            "email": "ethan.adams@example.com",
            "department": "Engineering",
            "position": "Software Architect",
            "salary": 125000,
            "hireDate": "2020-06-21",
            "status": "Active",
            "projects": ["System Redesign", "API Standards Development"],
            "performance": 5
          },
          {
            "id": 68,
            "name": "Victoria Thomas",
            "email": "victoria.thomas@example.com",
            "department": "Customer Support",
            "position": "Team Lead",
            "salary": 46000,
            "hireDate": "2021-08-12",
            "status": "Active",
            "projects": ["Customer Retention Initiative", "Support Workflow Optimization"],
            "performance": 4
          },
          {
            "id": 69,
            "name": "Mason White",
            "email": "mason.white@example.com",
            "department": "Engineering",
            "position": "Security Analyst",
            "salary": 88000,
            "hireDate": "2022-03-23",
            "status": "Active",
            "projects": ["Threat Assessment", "Security Patch Deployment"],
            "performance": 4
          },
          {
            "id": 70,
            "name": "Aria Lewis",
            "email": "aria.lewis@example.com",
            "department": "Design",
            "position": "Graphic Designer",
            "salary": 61000,
            "hireDate": "2019-09-15",
            "status": "Inactive",
            "projects": ["Marketing Materials", "Illustration Creation"],
            "performance": 3
          },
            {
              "id": 71,
              "name": "Liam Walker",
              "email": "liam.walker@example.com",
              "department": "Engineering",
              "position": "Full Stack Developer",
              "salary": 92000,
              "hireDate": "2021-07-12",
              "status": "Active",
              "projects": ["Web Application Development", "System Integration"],
              "performance": 4
            },
            {
              "id": 72,
              "name": "Sophia Mitchell",
              "email": "sophia.mitchell@example.com",
              "department": "Marketing",
              "position": "Content Strategist",
              "salary": 68000,
              "hireDate": "2020-02-20",
              "status": "Active",
              "projects": ["Content Planning", "SEO Optimization"],
              "performance": 5
            },
            {
              "id": 73,
              "name": "Elijah Turner",
              "email": "elijah.turner@example.com",
              "department": "IT",
              "position": "Technical Support Specialist",
              "salary": 54000,
              "hireDate": "2022-10-03",
              "status": "Active",
              "projects": ["Troubleshooting Operations", "User Training"],
              "performance": 4
            },
            {
              "id": 74,
              "name": "Charlotte Hernandez",
              "email": "charlotte.hernandez@example.com",
              "department": "Finance",
              "position": "Financial Analyst",
              "salary": 84000,
              "hireDate": "2021-03-18",
              "status": "Active",
              "projects": ["Budget Planning", "Cost Analysis"],
              "performance": 5
            },
            {
              "id": 75,
              "name": "Oliver Jackson",
              "email": "oliver.jackson@example.com",
              "department": "HR",
              "position": "Recruitment Coordinator",
              "salary": 57000,
              "hireDate": "2023-01-10",
              "status": "Active",
              "projects": ["Hiring Campaigns", "Employee Engagement"],
              "performance": 3
            },
            {
              "id": 76,
              "name": "Amelia Harris",
              "email": "amelia.harris@example.com",
              "department": "Engineering",
              "position": "Data Scientist",
              "salary": 105000,
              "hireDate": "2019-12-22",
              "status": "Active",
              "projects": ["Predictive Analytics", "Machine Learning Models"],
              "performance": 5
            },
            {
              "id": 77,
              "name": "James Lopez",
              "email": "james.lopez@example.com",
              "department": "Design",
              "position": "UI/UX Designer",
              "salary": 74000,
              "hireDate": "2020-09-01",
              "status": "Active",
              "projects": ["User Interface Design", "Accessibility Enhancement"],
              "performance": 4
            },
            {
              "id": 78,
              "name": "Emily Clark",
              "email": "emily.clark@example.com",
              "department": "Sales",
              "position": "Key Account Manager",
              "salary": 88000,
              "hireDate": "2022-06-25",
              "status": "Active",
              "projects": ["Client Relationship Management", "Sales Expansion"],
              "performance": 5
            },
            {
              "id": 79,
              "name": "William Gonzalez",
              "email": "william.gonzalez@example.com",
              "department": "Customer Support",
              "position": "Support Specialist",
              "salary": 48000,
              "hireDate": "2021-11-09",
              "status": "Active",
              "projects": ["Customer Queries Resolution", "Support Tickets Management"],
              "performance": 4
            },
            {
              "id": 80,
              "name": "Sofia Hall",
              "email": "sofia.hall@example.com",
              "department": "Marketing",
              "position": "Marketing Analyst",
              "salary": 70000,
              "hireDate": "2020-08-14",
              "status": "Active",
              "projects": ["Campaign Performance Analysis", "Market Trends Monitoring"],
              "performance": 5
            },
            {
              "id": 81,
              "name": "Henry Scott",
              "email": "henry.scott@example.com",
              "department": "Engineering",
              "position": "Frontend Developer",
              "salary": 80000,
              "hireDate": "2022-04-12",
              "status": "Active",
              "projects": ["Component Library Development", "UI Testing"],
              "performance": 4
            },
            {
              "id": 82,
              "name": "Chloe Adams",
              "email": "chloe.adams@example.com",
              "department": "Operations",
              "position": "Operations Manager",
              "salary": 93000,
              "hireDate": "2018-11-23",
              "status": "Active",
              "projects": ["Supply Chain Optimization", "Team Coordination"],
              "performance": 5
            },
            {
              "id": 83,
              "name": "Jackson Nelson",
              "email": "jackson.nelson@example.com",
              "department": "Engineering",
              "position": "DevOps Engineer",
              "salary": 99000,
              "hireDate": "2019-06-18",
              "status": "Active",
              "projects": ["CI/CD Pipeline Management", "Infrastructure Automation"],
              "performance": 5
            },
            {
              "id": 84,
              "name": "Lily Robinson",
              "email": "lily.robinson@example.com",
              "department": "HR",
              "position": "HR Generalist",
              "salary": 59000,
              "hireDate": "2021-10-03",
              "status": "Active",
              "projects": ["Employee Benefits Management", "Policy Implementation"],
              "performance": 3
            },
            {
              "id": 85,
              "name": "Mason Perez",
              "email": "mason.perez@example.com",
              "department": "IT",
              "position": "Cloud Engineer",
              "salary": 107000,
              "hireDate": "2020-01-20",
              "status": "Active",
              "projects": ["Cloud Infrastructure Deployment", "Data Migration"],
              "performance": 5
            },
            {
              "id": 86,
              "name": "Ava Martinez",
              "email": "ava.martinez@example.com",
              "department": "Finance",
              "position": "Accounts Payable Specialist",
              "salary": 61000,
              "hireDate": "2022-08-15",
              "status": "Active",
              "projects": ["Invoice Reconciliation", "Expense Reports Management"],
              "performance": 4
            },
            {
              "id": 87,
              "name": "Ethan Young",
              "email": "ethan.young@example.com",
              "department": "Engineering",
              "position": "Blockchain Developer",
              "salary": 130000,
              "hireDate": "2023-03-07",
              "status": "Active",
              "projects": ["Smart Contract Development", "Ledger Implementation"],
              "performance": 5
            },
            {
              "id": 88,
              "name": "Grace King",
              "email": "grace.king@example.com",
              "department": "Marketing",
              "position": "Event Coordinator",
              "salary": 57000,
              "hireDate": "2020-04-10",
              "status": "Active",
              "projects": ["Corporate Events Planning", "Vendor Management"],
              "performance": 4
            },
            {
              "id": 89,
              "name": "Luke Wright",
              "email": "luke.wright@example.com",
              "department": "Engineering",
              "position": "Systems Engineer",
              "salary": 87000,
              "hireDate": "2021-12-05",
              "status": "Active",
              "projects": ["System Optimization", "Uptime Monitoring"],
              "performance": 4
            },
            {
              "id": 90,
              "name": "Isabella Carter",
              "email": "isabella.carter@example.com",
              "department": "Design",
              "position": "Motion Designer",
              "salary": 73000,
              "hireDate": "2022-02-16",
              "status": "Active",
              "projects": ["Video Graphics Creation", "Animation Concepts"],
              "performance": 5
            }
          
          
        ]
    }